gtws-clone - allow a target directory name
Sometimes, I want two clones of the same project (for example, a test
version from someone else) in a workspace.  Allow overriding the
directory name of the clone to handle this case.

Signed-off-by: Daniel Gryniewicz <dang@fprintf.net>

diff --git a/gtws-clone b/gtws-clone
--- a/gtws-clone
+++ b/gtws-clone
@@ -21,12 +21,13 @@ fi
 
 # Set usage output
 DESCRIPTION="Clone a new repo into a workspace"
-USAGE="[-h |--help] [[-p <project> | --project=<project>] | [[-r <repo-base> | --repo-base=<repo-base>] [-s <submodule-base> | --submodule-base=<submodule-base>]]] [-b <branch> | --branch=<branch>] [-V | --verbose] <repo-name>"
+USAGE="[-h |--help] [[-p <project> | --project=<project>] | [[-r <repo-base> | --repo-base=<repo-base>] [-s <submodule-base> | --submodule-base=<submodule-base>]]] [-b <branch> | --branch=<branch>] [-d <directory> | --directory=<directory> ] [-V | --verbose] <repo-name>"
 LONGUSAGE="\t-h, --help\n\t\tPrint this help message
 \t-p <project>, --project=<project>\n\t\tClone from project; sets repo-base and submodule-base (default: ${GTWS_PROJECT:-none})
 \t-r <repo-base>, --repo-base=<repo-base>\n\t\tBase dir for repo (default: ${REPO_BASE:-none})
 \t-s <submodule-base>, --submodule-base=<submodule-base>\n\t\tBase dir for submodules (default: ${SUBMODULE_BASE:-none})
 \t-b <branch>, --branch=<branch>\n\t\tRepo branch (default: ${BRANCH})
+\t-d <directory>, --directory=<directory>\n\t\tDirectory to clone into.  Default: <repo-name>
 \t-V, --verbose\n\t\tBe verbose
 \t<repo-name>\n\t\tRepository name"
 
@@ -34,7 +35,7 @@ LONGUSAGE="\t-h, --help\n\t\tPrint this help message
 ME=$(basename $0)
 
 # Parse arguments
-ARGS=`getopt -o hVp:r:s:b: --long help,verbose,project:,repo-base:,submodule-base:,branch: -n "${ME}" -- "$@"`
+ARGS=`getopt -o hVp:r:s:b:d: --long help,verbose,project:,repo-base:,submodule-base:,branch:,directory: -n "${ME}" -- "$@"`
 
 if [ $? != 0 ] ; then
 	usage 
@@ -48,6 +49,7 @@ while true ; do
 		-r|--repo-base) REPO_BASE=$2 ; shift 2 ;;
 		-s|--submodule-base) SUBMODULE_BASE=$2 ; shift 2 ;;
 		-b|--branch) BRANCH=$2 ; shift 2 ;;
+		-d|--directory) DIRECTORY=$2 ; shift 2 ;;
 		-V|--verbose) export GTWS_VERBOSE=yes; shift ;;
 		--) shift ; break ;;
 		* ) usage "Invalid argument $1";;
@@ -77,7 +79,7 @@ cd "${GTWS_WS_PATH}" || die "Could not cd to ${GTWS_WS_PATH}"
 
 # Clone the repo.
 # XXX TODO - Allow overriding of clone function
-gtws_repo_clone "${REPO_BASE}" "${REPO}" "${BRANCH}" "${SUBMODULE_BASE}" || die "gtws_repo_clone failed"
+gtws_repo_clone "${REPO_BASE}" "${REPO}" "${BRANCH}" "${SUBMODULE_BASE}" "${DIRECTORY}" || die "gtws_repo_clone failed"
 
 # Set up the repo.
 # XXX TODO - Allow overriding of setup function
