Better handling of nested submodules
Store the sub-submodules in a subdir for that submodule.  Update clone,
mirror, and sync to work with this.

Signed-off-by: Daniel Gryniewicz <dang@fprintf.net>

diff --git a/gtws-mirror b/gtws-mirror
--- a/gtws-mirror
+++ b/gtws-mirror
@@ -93,40 +93,56 @@ if [ -z "${ONLY_SUBMODULES}" ]; then
 	git clone --mirror "${UPSTREAM}" || die "Failed to clone main mirror"
 fi
 
-function sm_mirror {
-	gtws_submodule_url ${1} url
+function sm_fetch_mirror {
+	local sub=${1}
+	local smbase=${2}
+	local rpath="${PWD}"
+	local url=$(gtws_submodule_url ${sub})
+	local sub_base=$(basename ${sub})
 	debug_print "url: $url"
 	if [ -z "${url}" ]; then
 		return
 	fi
 
 	local urlbase=$(basename ${url})
-	debug_print "url: $urlbase"
+	debug_print "urlbase: $urlbase"
 
-	if [ -d "${SUBMODULE_BASE}/${urlbase}" ]; then
-		# Already exists
-		echo "mirror for submodule ${urlbase} already exists; skipping"
-		return
+	if [ ! -d "${smbase}" ]; then
+		mkdir "${smbase}"
 	fi
 
-	cd "${SUBMODULE_BASE}" || die "failed to cd to submodule dir"
-	git clone --mirror "${url}" || die "Failed to clone submodule mirror ${urlbase}"
-	if [ ! -d "${urlbase}" ]; then
-		if [ -d "${urlbase}.git" ]; then
-			mv "${urlbase}.git" "${urlbase}"
+	if [ ! -d "${smbase}/${urlbase}" ]; then
+		cd "${smbase}" || die "failed to cd to submodule dir"
+		git clone --mirror "${url}" || die "Failed to clone submodule mirror ${urlbase}"
+		if [ ! -d "${urlbase}" ]; then
+			if [ -d "${urlbase}.git" ]; then
+				mv "${urlbase}.git" "${urlbase}"
+			fi
+		fi
+		if [ ! -d "${urlbase}" ]; then
+			die "Mirror for submodule in wrong location. Expected ${urlbase}"
 		fi
 	fi
-	if [ ! -d "${urlbase}" ]; then
-		die "Mirror for submodule in wrong location. Expected ${urlbase}"
-	fi
-	cd "${REPODIR}"
+
+	# Try for sub-sub modules
+	sm_mirror "${rpath}/${sub}" "${smbase}/${sub_base}_submodule"
+
+	cd "${rpath}"
 }
 
 # Mirror submodules
-cd "${REPODIR}"
-SUBPATHS=$(gtws_submodule_paths)
-for sub in ${SUBPATHS}; do
-	sm_mirror ${sub}
-done
+function sm_mirror {
+	local repodir=${1}
+	local smbase=${2}
+
+	debug_print "${FUNCNAME} trying ${repodir} ${smbase}"
+	cd "${repodir}"
+	local subpaths=$(gtws_submodule_paths)
+	for sub in ${subpaths}; do
+		sm_fetch_mirror ${sub} ${smbase}
+	done
+}
+
+sm_mirror "${REPODIR}" "${SUBMODULE_BASE}"
 
 echo "Done"
