all - configurable origin, default rtos, cleanup
- GTWS_ORIGIN now allows configuration of origin
- set_default_rtos now sets the default RTOS given a gated version.  It
  allows a single place to set this.
- Cleanup
	- Make functions use local variables
	- Use WSBASE everywhere for origin

diff --git a/mkws b/mkws
--- a/mkws
+++ b/mkws
@@ -5,16 +5,6 @@
 
 GATED=$(basename "${PWD}")
 
-case "${GATED}" in
-	trunk) RTOS="itrunk" ;;
-	3.3) RTOS="i11.0" ;;
-	3.2) RTOS="i10.0" ;;
-	3.1) RTOS="i5.0" ;;
-	*) RTOS="itrunk" ;;
-esac
-ORIGIN="${HOME}/origin"
-WSDIRS="routing docs gatt"
-
 # Set usage output
 USAGE="[-h |--help] [-a | --all-rtos] [-r <rtos> | --rtos=<rtos>] [-v <version> | --version=<version>] <name>"
 LONGUSAGE="\t-h, --help\n\t\tPrint this help message
@@ -25,6 +15,10 @@ LONGUSAGE="\t-h, --help\n\t\tPrint this help message
 
 # Standard functions
 source ${GTWS}/gtws.sh
+
+set_default_rtos "${GATED}"
+WSBASE="${GTWS_ORIGIN:-${HOME}/origin}"
+WSDIRS="routing docs gatt"
 
 # Script name
 ME=$(basename $0)
@@ -57,12 +51,12 @@ WSPATH=$(readlink -f "${1}")
 WSNAME=$(basename "${WSPATH}")
 
 # Workspace check
-WS="${ORIGIN}/${GATED}"
+WS="${WSBASE}/${GATED}"
 if [ ! -d "${WS}" ]; then
 	die "No workspace for ${WS}"
 fi
-if [ ! -d "${ORIGIN}/${RTOS}" ]; then
-	die "No ${RTOS} in ${ORIGIN}"
+if [ ! -d "${WSBASE}/${RTOS}" ]; then
+	die "No ${RTOS} in ${WSBASE}"
 fi
 
 # Workspace contents check
@@ -103,15 +97,16 @@ fi
 
 # Set up GateD
 cd "${WSPATH}/routing" || die "failed to cd to routing"
-maketags
+export SYSTEM_HDRS="../${RTOS}/INTEGRITY-include /share/ghs/comp/current"
+maketags -c
 
 # Set up GATT
 cd "${WSPATH}/gatt" || die "failed to cd to gatt"
-maketags -p
+maketags -p -c
 
 # Add dmltools to docs
 cd "${WSPATH}/docs" || die "failed to cd to docs"
-git clone "${ORIGIN}/dmltools" || die "failed to clone dmltools"
+git clone "${WSBASE}/dmltools" || die "failed to clone dmltools"
 
 # Set up workdirs
 echo "Making workdirs"
diff --git a/rtos-clone b/rtos-clone
--- a/rtos-clone
+++ b/rtos-clone
@@ -3,7 +3,7 @@
 # Clone an rtos into a workspace
 #
 
-ORIGIN="${HOME}/origin"
+WSBASE="${GTWS_ORIGIN:-${HOME}/origin}"
 WSPATH="${PWD}"
 
 # Set usage output
@@ -42,7 +42,7 @@ if [ -n "${1}" ]; then
 fi
 
 if [ -n "${ALL}" ]; then
-	cd "${ORIGIN}"
+	cd "${WSBASE}"
 	RTOS=$(/bin/ls -d i*)
 fi
 
@@ -54,8 +54,8 @@ cd "${WSPATH}"
 
 for i in ${RTOS}; do
 	echo "cloning $i"
-	git clone "${ORIGIN}/${i}" || die "failed to clone ${i}"
-	cp "${ORIGIN}/${i}/.git/info/exclude" "${i}/.git/info/" || die "failed to copy exclude"
+	git clone "${WSBASE}/${i}" || die "failed to clone ${i}"
+	cp "${WSBASE}/${i}/.git/info/exclude" "${i}/.git/info/" || die "failed to copy exclude"
 	echo "Setting up $i"
 	cd "${WSPATH}/${i}/modules/ghs" || die "failed to cd to ${i}/modules/ghs"
 	ln -s "${WSPATH}/routing" "gated" || die "failed to symlink gated"
