Cleanup - Prefix GTWS on WSPATH and WSNAME
- Rename WSPATH to GTWS_WSPATH and WSNAME to GTWS_WSNAME
- Export them for use in scripts/shell

diff --git a/mkws b/mkws
--- a/mkws
+++ b/mkws
@@ -4,7 +4,7 @@
 #
 
 function GTWScleanup {
-	rm -rf "${WSPATH}"
+	rm -rf "${GTWS_WSPATH}"
 }
 
 # Standard functions
@@ -80,19 +80,19 @@ elif [ "${PROJECT}" != "${GTWS_PROJECT}" ]; then
 	die "In wrong project dir: expected ${PROJECT} got ${GTWS_PROJECT}"
 fi
 
-WSPATH=$(readlink -f "${1}")
-WSNAME=$(basename "${WSPATH}")
+GTWS_WSPATH=$(readlink -f "${1}")
+GTWS_WSNAME=$(basename "${GTWS_WSPATH}")
 
 # Target directory check
-if [ -d "${WSPATH}" ]; then
-	die "Workspace ${WSPATH} already exists"
+if [ -d "${GTWS_WSPATH}" ]; then
+	die "Workspace ${GTWS_WSPATH} already exists"
 fi
 
 # Set up the environment
-mkdir -p "${WSPATH}" || die "Failed to mkdir ${WSPATH}"
-cd "${WSPATH}"
-cp "${GTWSLOC}"/gtwsrc "${WSPATH}"/.gtwsrc
-source "${WSPATH}"/.gtwsrc
+mkdir -p "${GTWS_WSPATH}" || die "Failed to mkdir ${GTWS_WSPATH}"
+cd "${GTWS_WSPATH}"
+cp "${GTWSLOC}"/gtwsrc "${GTWS_WSPATH}"/.gtwsrc
+source "${GTWS_WSPATH}"/.gtwsrc
 
 # Origin
 O="${GTWS_ORIGIN:=${HOME}/origin}"
@@ -119,21 +119,21 @@ if [ -z "${HAS_CLONE}" ]; then
 fi
 
 # Make workspace
-echo "Making workspace for ${VERSION}:${TARGET} in ${WSPATH}"
+echo "Making workspace for ${VERSION}:${TARGET} in ${GTWS_WSPATH}"
 # Made directory above
 
-touch "${WSPATH}/.sdirs"
+touch "${GTWS_WSPATH}/.sdirs"
 
 if [ -n "${HAS_CLONE}" ]; then
 	# Project provided a clone
-	gtws_project_clone ${O} ${PROJECT} ${VERSION} || die "clone failed"
+	gtws_project_clone ${O} ${PROJECT} ${VERSION} ${GTWS_WSNAME} || die "clone failed"
 else
 	# Default clone
 	gtws_project_clone_default ${O} ${PROJECT} ${VERSION} || die "clone failed"
 fi
 
 if [ -n "$(declare -F | grep "gtws_project_setup")" ]; then
-	gtws_project_setup ${WSNAME} ${O} ${PROJECT} ${VERSION} || die "setup failed"
+	gtws_project_setup ${GTWS_WSNAME} ${O} ${PROJECT} ${VERSION} || die "setup failed"
 fi
 
 echo "Done"
diff --git a/rmws b/rmws
--- a/rmws
+++ b/rmws
@@ -39,21 +39,21 @@ if [ -z "${1}" ]; then
 	usage "Must give a workspace name"
 fi
 
-WSPATH=$(readlink -f "${1}")
-WSNAME=$(basename "${WSPATH}")
+GTWS_WSPATH=$(readlink -f "${1}")
+GTWS_WSNAME=$(basename "${GTWS_WSPATH}")
 
 # Target directory check
-if [ ! -d "${WSPATH}" ]; then
-	die "Workspace ${WSPATH} doesn't exist"
+if [ ! -d "${GTWS_WSPATH}" ]; then
+	die "Workspace ${GTWS_WSPATH} doesn't exist"
 fi
 
 # Cleanup
 if [ -n "$(declare -F | grep "gtws_project_cleanup")" ]; then
 	basedir="${PWD}"
-	cd "${WSPATH}"
-	gtws_project_cleanup ${WSNAME} ${PROJECT} ${VERSION} || die "cleanup failed"
+	cd "${GTWS_WSPATH}"
+	gtws_project_cleanup ${GTWS_WSNAME} ${PROJECT} ${VERSION} || die "cleanup failed"
 	cd "${basedir}"
 fi
 
 # Nuke workspace
-rm -rf "${WSPATH}"
+rm -rf "${GTWS_WSPATH}"
diff --git a/rtos-clone b/rtos-clone
--- a/rtos-clone
+++ b/rtos-clone
@@ -19,7 +19,7 @@ if [ ! -f ".gtwsrc" ]; then
 	die "${PWD} is not a workspace"
 fi
 source ".gtwsrc"
-WSPATH="${PWD}"
+GTWS_WSPATH="${PWD}"
 GTWS_ORIGIN="${GTWS_ORIGIN:-${HOME}/origin}"
 
 # Script name
@@ -58,7 +58,7 @@ if [ -z "${RTOS}" ]; then
 	usage "Must give an rtos version"
 fi
 
-cd "${WSPATH}"
+cd "${GTWS_WSPATH}"
 
 for i in ${RTOS}; do
 	if [ ! -d "${GTWS_ORIGIN}/${i}" ]; then
@@ -73,20 +73,20 @@ for i in ${RTOS}; do
 		fi
 	done
 	# Detect directory
-	if [ -d "${WSPATH}/${i}/rtos/pcx86" ]; then
-		RDIR="${WSPATH}/${i}/rtos"
+	if [ -d "${GTWS_WSPATH}/${i}/rtos/pcx86" ]; then
+		RDIR="${GTWS_WSPATH}/${i}/rtos"
 		# Can't patch this type
 		unset PATCH
-	elif [ -d "${WSPATH}/${i}/pcx86" ]; then
-		RDIR="${WSPATH}/${i}"
+	elif [ -d "${GTWS_WSPATH}/${i}/pcx86" ]; then
+		RDIR="${GTWS_WSPATH}/${i}"
 	else
-		die "Cannot find target dir in ${WSPATH}/${i}"
+		die "Cannot find target dir in ${GTWS_WSPATH}/${i}"
 	fi
 	if [ -n "${PATCH}" ]; then
-		if [ -d "${WSPATH}/gatt/patches/${i}" ]; then
+		if [ -d "${GTWS_WSPATH}/gatt/patches/${i}" ]; then
 			echo "Applying GATT patch"
 			cd "${RDIR}" || die "failed to cd to ${RDIR}"
-			git am --whitespace=nowarn "${WSPATH}/gatt/patches/${i}/"*.patch || die "git am failed"
+			git am --whitespace=nowarn "${GTWS_WSPATH}/gatt/patches/${i}/"*.patch || die "git am failed"
 		else
 			echo "No patches for ${i}; skipping"
 		fi
@@ -100,10 +100,10 @@ for i in ${RTOS}; do
 	sed -i "s#@GTWSRDIR@#${RDIR}#" "${RDIR}/Makefile" || die "rdir sed failed"
 	echo "Setting up $i"
 	cd "${RDIR}/modules/ghs" || die "failed to cd to ${RDIR}/modules/ghs"
-	ln -s "${WSPATH}/routing" "gated" || die "failed to symlink gated"
+	ln -s "${GTWS_WSPATH}/routing" "gated" || die "failed to symlink gated"
 	cd "${RDIR}" || die "failed to cd to ${RDIR}"
 	./setup > /dev/null 2>&1
-	cd "${WSPATH}"
+	cd "${GTWS_WSPATH}"
 	echo ""
 done
 
