gtws-clone - Clone a repo into a workspace
Add a new command to clone a repo into an existing workspace.  It does
the full setup for the new repo.

This makes several changes:
- Add a default gtws_project_setup_default in gtws.sh that does the
  default setup stuff all my workspaces already did.
- Split gtws_clone_repo from gtws_project_clone_default so that it can
  be called in gtws-clone
- Split gtws_setup_repo from gtws_project_setup_default so that it can
  be called from gtws-clone

diff --git a/mkws b/mkws
--- a/mkws
+++ b/mkws
@@ -144,8 +144,10 @@ else
 	gtws_project_clone_default "${O}" "${PROJECT}" "${VERSION}" "${GTWS_WSNAME}" || die "clone failed"
 fi
 
-if [ -n "$(declare -F | grep "gtws_project_setup")" ]; then
+if [ -n "$(declare -F | grep "\<gtws_project_setup\>")" ]; then
 	gtws_project_setup "${GTWS_WSNAME}" "${O}" "${PROJECT}" "${VERSION}" || die "setup failed"
+else
+	gtws_project_setup_default "${GTWS_WSNAME}" "${O}" "${PROJECT}" "${VERSION}" || die "setup failed"
 fi
 
 echo "Done"
