mkws - Allow a project to have WS as origin
Allow mkws to clone a workspace from another workspace, either local or
remote.  In the case where it's remote, skip repo checks.

diff --git a/mkws b/mkws
--- a/mkws
+++ b/mkws
@@ -101,9 +101,6 @@ HAS_CLONE=$(declare -F | grep "\<gtws_project_clone\>")
 echo "$HAS_CLONE"
 if [ -z "${HAS_CLONE}" ]; then
 	gtws_opv "${O}" "${PROJECT}" "${VERSION}" opv
-	if [ ! -d "${opv}" ]; then
-		die "No origin for ${origin} ${project} ${version}"
-	fi
 
 	# Workspace contents check
 	repos=${GTWS_PROJECT_REPOS}
@@ -136,14 +133,14 @@ touch "${GTWS_WSPATH}/.sdirs"
 
 if [ -n "${HAS_CLONE}" ]; then
 	# Project provided a clone
-	gtws_project_clone ${O} ${PROJECT} ${VERSION} ${GTWS_WSNAME} || die "clone failed"
+	gtws_project_clone "${O}" "${PROJECT}" "${VERSION}" "${GTWS_WSNAME}" || die "clone failed"
 else
 	# Default clone
-	gtws_project_clone_default ${O} ${PROJECT} ${VERSION} || die "clone failed"
+	gtws_project_clone_default "${O}" "${PROJECT}" "${VERSION}" "${GTWS_WSNAME}" || die "clone failed"
 fi
 
 if [ -n "$(declare -F | grep "gtws_project_setup")" ]; then
-	gtws_project_setup ${GTWS_WSNAME} ${O} ${PROJECT} ${VERSION} || die "setup failed"
+	gtws_project_setup "${GTWS_WSNAME}" "${O}" "${PROJECT}" "${VERSION}" || die "setup failed"
 fi
 
 echo "Done"
