Submodules - die()s break lots of things; unconditionally succeed
Signed-off-by: Daniel Gryniewicz <dang@fprintf.net>

diff --git a/mkws b/mkws
--- a/mkws
+++ b/mkws
@@ -109,7 +109,7 @@ source "${GTWS_WSPATH}"/.gtwsrc
 O="${GTWS_ORIGIN:=${HOME}/origin}"
 
 if [ -z "${SUBMODULE_BASE}" ]; then
-	SUBMODULE_BASE=$(gtws_smopvn "${GTWS_SUBMODULE_ORIGIN:-${O}}" "${PROJECT}" "${VERSION}" "${GTWS_WSNAME}")
+	gtws_smopvn "${GTWS_SUBMODULE_ORIGIN:-${O}}" "${PROJECT}" "${VERSION}" "${GTWS_WSNAME}" SUBMODULE_BASE || die "Could not get SUBMODULE_BASE"
 fi
 
 HAS_CLONE=$(declare -F | grep "\<gtws_project_clone\>")
