rtos-clone - Add a Makefile to the rtos
Install a Makefile with each rtos that uses the correct compiler for
that rtos version.

diff --git a/rtos-clone b/rtos-clone
--- a/rtos-clone
+++ b/rtos-clone
@@ -3,9 +3,6 @@
 # Clone an rtos into a workspace
 #
 
-WSBASE="${GTWS_ORIGIN:-${HOME}/origin}"
-WSPATH="${PWD}"
-
 # Set usage output
 USAGE="[-h |--help] [-a | --all-rtos] <rtos> [<rtos> ...]"
 LONGUSAGE="\t-h, --help\n\t\tPrint this help message
@@ -14,6 +11,9 @@ LONGUSAGE="\t-h, --help\n\t\tPrint this help message
 
 # Standard functions
 source ${GTWS}/gtws.sh
+
+WSBASE="${GTWS_ORIGIN:-${HOME}/origin}"
+WSPATH="${PWD}"
 
 # Script name
 ME=$(basename $0)
@@ -56,6 +56,10 @@ for i in ${RTOS}; do
 	echo "cloning $i"
 	git clone "${WSBASE}/${i}" || die "failed to clone ${i}"
 	cp "${WSBASE}/${i}/.git/info/exclude" "${i}/.git/info/" || die "failed to copy exclude"
+	echo "Creating makefile"
+	set_default_comp "${i}"
+	cp "${GTWS}/Makefile" "${WSPATH}/${i}" || die "Couldn't copy Makefile"
+	sed -i "s#@GTWSGBUILD@#${GTCOMP}/gbuild#" "${WSPATH}/${i}/Makefile" || die "sed failed"
 	echo "Setting up $i"
 	cd "${WSPATH}/${i}/modules/ghs" || die "failed to cd to ${i}/modules/ghs"
 	ln -s "${WSPATH}/routing" "gated" || die "failed to symlink gated"
