rtos-clone - handle cloning checkouts with rtos at top level

diff --git a/rtos-clone b/rtos-clone
--- a/rtos-clone
+++ b/rtos-clone
@@ -59,6 +59,9 @@ fi
 cd "${WSPATH}"
 
 for i in ${RTOS}; do
+	if [ ! -d "${GTWS_ORIGIN}/${i}" ]; then
+		die "No origin for ${i}"
+	fi
 	echo "cloning $i"
 	git clone "${GTWS_ORIGIN}/${i}" || die "failed to clone ${i}"
 	cp "${GTWS_ORIGIN}/${i}/.git/info/exclude" "${i}/.git/info/" || die "failed to copy exclude"
@@ -67,14 +70,22 @@ for i in ${RTOS}; do
 			cp "${GTWS_ORIGIN}/${i}/${f}" "${i}/" || die "failed to copy ${f}"
 		fi
 	done
+	# Detect directory
+	if [ -d "${WSPATH}/${i}/rtos/pcx86" ]; then
+		RDIR="${WSPATH}/${i}/rtos"
+	elif [ -d "${WSPATH}/${i}/pcx86" ]; then
+		RDIR="${WSPATH}/${i}"
+	else
+		die "Cannot find target dir in ${WSPATH}/${i}"
+	fi
 	echo "Creating makefile"
 	set_default_comp "${i}"
-	cp "${GTWSLOC}/Makefile" "${WSPATH}/${i}" || die "Couldn't copy Makefile"
-	sed -i "s#@GTWSGBUILD@#${GTWS_COMPILER_PATH}/gbuild#" "${WSPATH}/${i}/Makefile" || die "sed failed"
+	cp "${GTWSLOC}/Makefile" "${RDIR}" || die "Couldn't copy Makefile"
+	sed -i "s#@GTWSGBUILD@#${GTWS_COMPILER_PATH}/gbuild#" "${RDIR}/Makefile" || die "sed failed"
 	echo "Setting up $i"
-	cd "${WSPATH}/${i}/modules/ghs" || die "failed to cd to ${i}/modules/ghs"
+	cd "${RDIR}/modules/ghs" || die "failed to cd to ${RDIR}/modules/ghs"
 	ln -s "${WSPATH}/routing" "gated" || die "failed to symlink gated"
-	cd "${WSPATH}/${i}" || die "failed to cd to ${i}"
+	cd "${RDIR}" || die "failed to cd to ${RDIR}"
 	./setup > /dev/null 2>&1
 	cd "${WSPATH}"
 	echo ""
