rtos - make rtos-[clone|update] copy extra files

diff --git a/rtos-clone b/rtos-clone
--- a/rtos-clone
+++ b/rtos-clone
@@ -19,6 +19,7 @@ if [ ! -f ".gtwsrc" ]; then
 fi
 source ".gtwsrc"
 WSPATH="${PWD}"
+GTWS_ORIGIN="${GTWS_ORIGIN:-${HOME}/origin}"
 
 # Script name
 ME=$(basename $0)
@@ -47,7 +48,7 @@ if [ -n "${1}" ]; then
 fi
 
 if [ -n "${ALL}" ]; then
-	cd "${GTWS_ORIGIN:=${HOME}/origin}"
+	cd "${GTWS_ORIGIN}"
 	RTOS=$(/bin/ls -d i*)
 fi
 
@@ -61,6 +62,11 @@ for i in ${RTOS}; do
 	echo "cloning $i"
 	git clone "${GTWS_ORIGIN}/${i}" || die "failed to clone ${i}"
 	cp "${GTWS_ORIGIN}/${i}/.git/info/exclude" "${i}/.git/info/" || die "failed to copy exclude"
+	for f in ${GTWS_EXTRA_FILES}; do
+		if [ -f "${GTWS_ORIGIN}/${i}/${f}" ]; then
+			cp "${GTWS_ORIGIN}/${i}/${f}" "${i}/" || die "failed to copy ${f}"
+		fi
+	done
 	echo "Creating makefile"
 	set_default_comp "${i}"
 	cp "${GTWSLOC}/Makefile" "${WSPATH}/${i}" || die "Couldn't copy Makefile"
diff --git a/rtos-update b/rtos-update
--- a/rtos-update
+++ b/rtos-update
@@ -15,6 +15,13 @@ LONGUSAGE="\t-h, --help\n\t\tPrint this help message
 GTWSLOC=$(readlink -f $(dirname "$0"))
 source ${GTWSLOC}/gtws.sh
 
+# Workspace settings
+if [ ! -f ".gtwsrc" ]; then
+	die "${PWD} is not a workspace"
+fi
+source ".gtwsrc"
+GTWS_ORIGIN="${GTWS_ORIGIN:-${HOME}/origin}"
+
 # Script name
 ME=$(basename $0)
 
@@ -50,6 +57,12 @@ fi
 
 for i in ${RTOS}; do
 	echo "updating $i"
+	cp "${GTWS_ORIGIN}/${i}/.git/info/exclude" "${i}/.git/info/" || die "failed to copy exclude"
+	for f in ${GTWS_EXTRA_FILES}; do
+		if [ -f "${GTWS_ORIGIN}/${i}/${f}" ]; then
+			cp "${GTWS_ORIGIN}/${i}/${f}" "${i}/" || die "failed to copy ${f}"
+		fi
+	done
 	cd "${i}"
 	git pull --rebase || die "Pull failed for ${i}"
 	cd "${WSPATH}"
